server:
  port: 8000
  servlet:
    contextPath: /api
spring:
  data:
    rest:
      basePath: /rest
  datasource:
    url: jdbc:mariadb://localhost:3306/wolfwr?createDatabaseIfNotExist=true
    username: root
    password: Nirav@29
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect