server:
  port: 8000
  servlet:
    contextPath: /api
spring:
  data:
    rest:
      basePath: /rest
  datasource:
    url: jdbc:mariadb://wolfwr.cowh7ovkjohy.us-east-2.rds.amazonaws.com:3306/wolfwr?createDatabaseIfNotExist=true
    username: root
    password: SimStudent
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect